"""initial schema

Revision ID: 9ef238497e99
Revises: 
Create Date: 2026-04-20 16:24:03.691872+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ef238497e99'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Idempotent bootstrap. If the DB was created pre-alembic by
    # init_db()/metadata.create_all(), the tables already exist; let alembic
    # just stamp this revision into alembic_version and continue.
    bind = op.get_bind()
    if sa.inspect(bind).has_table("feeds"):
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feeds',
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('site_url', sa.String(length=2048), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('etag', sa.String(length=256), nullable=True),
    sa.Column('last_modified', sa.String(length=256), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_successful_fetch_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feeds')),
    sa.UniqueConstraint('url', name=op.f('uq_feeds_url'))
    )
    op.create_table('feed_entries',
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('link', sa.String(length=2048), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=256), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('title_translated', sa.String(length=1024), nullable=True),
    sa.Column('summary_translated', sa.Text(), nullable=True),
    sa.Column('translation_language', sa.String(length=10), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], name=op.f('fk_feed_entries_feed_id_feeds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feed_entries'))
    )
    with op.batch_alter_table('feed_entries', schema=None) as batch_op:
        batch_op.create_index('ix_feed_entries_feed_guid', ['feed_id', 'guid'], unique=True)
        batch_op.create_index('ix_feed_entries_published', ['published_at'], unique=False)

    op.create_table('subscriptions',
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('platform_user_id', sa.String(length=64), nullable=False),
    sa.Column('platform_channel_id', sa.String(length=64), nullable=False),
    sa.Column('platform_guild_id', sa.String(length=64), nullable=True),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('translate', sa.Boolean(), nullable=False),
    sa.Column('target_language', sa.String(length=10), nullable=False),
    sa.Column('show_summary', sa.Boolean(), nullable=False),
    sa.Column('show_image', sa.Boolean(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_entry_guid', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], name=op.f('fk_subscriptions_feed_id_feeds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index('ix_subscriptions_active', ['is_active'], unique=False)
        batch_op.create_index('ix_subscriptions_channel_feed', ['platform', 'platform_channel_id', 'feed_id'], unique=True)
        batch_op.create_index('ix_subscriptions_platform_channel', ['platform', 'platform_channel_id'], unique=False)

    op.create_table('sent_entries',
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['feed_entries.id'], name=op.f('fk_sent_entries_entry_id_feed_entries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_sent_entries_subscription_id_subscriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sent_entries'))
    )
    with op.batch_alter_table('sent_entries', schema=None) as batch_op:
        batch_op.create_index('ix_sent_entries_sent_at', ['sent_at'], unique=False)
        batch_op.create_index('ix_sent_entries_subscription_entry', ['subscription_id', 'entry_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sent_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_sent_entries_subscription_entry')
        batch_op.drop_index('ix_sent_entries_sent_at')

    op.drop_table('sent_entries')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index('ix_subscriptions_platform_channel')
        batch_op.drop_index('ix_subscriptions_channel_feed')
        batch_op.drop_index('ix_subscriptions_active')

    op.drop_table('subscriptions')
    with op.batch_alter_table('feed_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_feed_entries_published')
        batch_op.drop_index('ix_feed_entries_feed_guid')

    op.drop_table('feed_entries')
    op.drop_table('feeds')
    # ### end Alembic commands ###
