"""add filter_rule and was_filtered

Revision ID: ed46ab8042bd
Revises: 9ef238497e99
Create Date: 2026-04-22 01:16:40.053501+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed46ab8042bd'
down_revision: Union[str, None] = '9ef238497e99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Existing sent_entries rows pre-date this column; backfill them with
    # False (server_default) so the NOT NULL constraint is satisfied. The
    # default is a one-time migration convenience — new rows get their value
    # from the ORM `default=False`.
    with op.batch_alter_table('sent_entries', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'was_filtered', sa.Boolean(),
                nullable=False, server_default=sa.false(),
            )
        )

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filter_rule', sa.JSON(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('filter_rule')

    with op.batch_alter_table('sent_entries', schema=None) as batch_op:
        batch_op.drop_column('was_filtered')

    # ### end Alembic commands ###
