"""add channel_digests table

Revision ID: 8e1b84612c65
Revises: ed46ab8042bd
Create Date: 2026-04-22 04:51:30.083162+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e1b84612c65'
down_revision: Union[str, None] = 'ed46ab8042bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_digests',
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('platform_channel_id', sa.String(length=64), nullable=False),
    sa.Column('platform_guild_id', sa.String(length=64), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule', sa.String(length=16), nullable=False),
    sa.Column('delivery_hour_utc', sa.Integer(), nullable=False),
    sa.Column('delivery_weekday', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('include_filtered', sa.Boolean(), nullable=False),
    sa.Column('max_articles', sa.Integer(), nullable=False),
    sa.Column('last_delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_digests'))
    )
    with op.batch_alter_table('channel_digests', schema=None) as batch_op:
        batch_op.create_index('ix_channel_digests_enabled', ['enabled'], unique=False)
        batch_op.create_index('ix_channel_digests_platform_channel', ['platform', 'platform_channel_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel_digests', schema=None) as batch_op:
        batch_op.drop_index('ix_channel_digests_platform_channel')
        batch_op.drop_index('ix_channel_digests_enabled')

    op.drop_table('channel_digests')
    # ### end Alembic commands ###
